"""Обновление бд5

Revision ID: 1083adbe2ae7
Revises: 6d31b8e58850
Create Date: 2024-06-12 21:49:43.328945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1083adbe2ae7'
down_revision = '6d31b8e58850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_cover_id_covers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_cover_id_covers'), 'covers', ['cover_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_cover_id_covers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_cover_id_covers', 'covers', ['cover_id'], ['id'])

    # ### end Alembic commands ###
