"""Обновление бд6

Revision ID: 5ac07469e67e
Revises: 1083adbe2ae7
Create Date: 2024-06-12 22:22:03.285529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac07469e67e'
down_revision = '1083adbe2ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_genre_book_id_books', type_='foreignkey')
        batch_op.drop_constraint('fk_book_genre_genre_id_genres', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_book_genre_genre_id_genres'), 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_book_genre_book_id_books'), 'books', ['book_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('cover_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('md5_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.alter_column('md5_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('mime_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('cover_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_book_genre_book_id_books'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_book_genre_genre_id_genres'), type_='foreignkey')
        batch_op.create_foreign_key('fk_book_genre_genre_id_genres', 'genres', ['genre_id'], ['id'])
        batch_op.create_foreign_key('fk_book_genre_book_id_books', 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###
