"""Обновление бд3

Revision ID: 84fc65218c11
Revises: 979333f6ffe7
Create Date: 2024-06-12 15:00:51.743987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84fc65218c11'
down_revision = '979333f6ffe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_genre_book_id_books')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_book_genre_genre_id_genres')),
    sa.PrimaryKeyConstraint('book_id', 'genre_id', name=op.f('pk_book_genre'))
    )
    op.drop_table('books_genres')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=255), nullable=False))

    op.create_table('books_genres',
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('genre_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='fk_books_genres_book_id_books'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='fk_books_genres_genre_id_genres'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('book_genre')
    # ### end Alembic commands ###
